local p = require("kanagawa_dragon_blur.palette")
return {
    -- Links a grupos estándar, como hace kanagawa.nvim
    DevIconLua        = { link = "Function" },
    DevIconJs         = { link = "Special" },
    DevIconTs         = { link = "Type" },
    DevIconJson       = { link = "Constant" },
    DevIconHtml       = { link = "Tag" },
    DevIconCss        = { link = "Type" },
    DevIconScss       = { link = "PreProc" },
    DevIconMd         = { link = "String" },
    DevIconVim        = { link = "Function" },
    DevIconGitignore  = { link = "Error" },
    DevIconDockerfile = { link = "Type" },
    DevIconSh         = { link = "Function" },
    DevIconZsh        = { link = "Function" },
    DevIconLock       = { link = "Boolean" },
    DevIconToml       = { link = "Constant" },
    DevIconYaml       = { link = "Constant" },
    DevIconFolder     = { link = "Directory" },
    DevIconDefault    = { link = "Identifier" },
    DevIconC          = { link = "Type" },
    DevIconCpp        = { link = "Type" },
    DevIconPy         = { link = "Special" },
    DevIconRb         = { link = "Error" },
    DevIconGo         = { link = "Type" },
    DevIconRs         = { link = "Constant" },
    DevIconPhp        = { link = "PreProc" },
    DevIconJava       = { link = "Error" },
    DevIconTxt        = { link = "Comment" },
    DevIconSvg        = { link = "String" },
    DevIconSvelte     = { link = "Boolean" },
    DevIconAstro      = { link = "Boolean" },
}
