local p = require("kanagawa_dragon_blur.palette")

return {
	-- Ventanas y selección: transparencia estructural, foco con fondo discreto.
	FzfLuaNormal = { fg = p.fg, bg = "NONE" },
	FzfLuaBorder = { fg = p.border, bg = "NONE" },
	FzfLuaTitle = { fg = p.title, bg = "NONE", bold = true },
	FzfLuaTitleFlags = { fg = p.ui_secondary, bg = "NONE" },
	FzfLuaHelpNormal = { link = "FzfLuaNormal" },
	FzfLuaHelpBorder = { link = "FzfLuaBorder" },
	FzfLuaPreviewNormal = { link = "FzfLuaNormal" },
	FzfLuaPreviewBorder = { link = "FzfLuaBorder" },
	FzfLuaPreviewTitle = { link = "FzfLuaTitle" },
	FzfLuaCursor = { link = "Cursor" },
	FzfLuaCursorLine = { fg = p.fg, bg = p.selection },
	FzfLuaCursorLineNr = { fg = p.accent, bg = p.selection },
	FzfLuaSearch = { fg = p.accent, bg = p.selection, bold = true },
	FzfLuaScrollBorderEmpty = { link = "FzfLuaBorder" },
	FzfLuaScrollBorderFull = { fg = p.ui_secondary, bg = "NONE" },
	FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
	FzfLuaScrollFloatFull = { link = "PmenuThumb" },

	-- Rutas, cabeceras y estados sin los colores vivos predeterminados.
	FzfLuaDirIcon = { fg = p.blue },
	FzfLuaDirPart = { fg = p.fg_muted },
	FzfLuaFilePart = { fg = p.fg },
	FzfLuaHeaderBind = { fg = p.accent },
	FzfLuaHeaderText = { fg = p.ui_secondary },
	FzfLuaPathColNr = { fg = p.fg_muted },
	FzfLuaPathLineNr = { fg = p.ui_secondary },
	FzfLuaLivePrompt = { fg = p.accent },
	FzfLuaLiveSym = { fg = p.purple },
	FzfLuaBufId = { fg = p.fg_muted },
	FzfLuaBufName = { fg = p.fg },
	FzfLuaBufLineNr = { fg = p.fg_muted },
	FzfLuaBufNr = { fg = p.ui_secondary },
	FzfLuaBufFlagCur = { fg = p.accent },
	FzfLuaBufFlagAlt = { fg = p.ui_secondary },
	FzfLuaTabTitle = { link = "FzfLuaTitle" },
	FzfLuaTabMarker = { fg = p.accent, bold = true },
	FzfLuaCmdEx = { fg = p.purple },
	FzfLuaCmdBuf = { fg = p.green },
	FzfLuaCmdGlobal = { fg = p.blue },

	-- Colores del proceso fzf cuando fzf_colors = true (predeterminado de LazyVim).
	FzfLuaFzfNormal = { link = "FzfLuaNormal" },
	FzfLuaFzfCursorLine = { link = "FzfLuaCursorLine" },
	FzfLuaFzfMatch = { fg = p.accent, bold = true },
	FzfLuaFzfBorder = { link = "FzfLuaBorder" },
	FzfLuaFzfScrollbar = { fg = p.ui_secondary },
	FzfLuaFzfSeparator = { fg = p.border },
	FzfLuaFzfGutter = { link = "FzfLuaNormal" },
	FzfLuaFzfHeader = { fg = p.ui_secondary },
	FzfLuaFzfInfo = { fg = p.fg_muted },
	FzfLuaFzfPointer = { fg = p.accent },
	FzfLuaFzfMarker = { fg = p.green },
	FzfLuaFzfSpinner = { fg = p.accent },
	FzfLuaFzfPrompt = { fg = p.accent },
	FzfLuaFzfQuery = { link = "FzfLuaNormal" },
}
