local p = require("kanagawa_dragon_blur.palette")

return {
    -- Links estilo kanagawa.nvim para máxima compatibilidad y override
    NavicIconsFile          = { link = "Directory" },
    NavicIconsModule        = { link = "Special" },
    NavicIconsNamespace     = { link = "Type" },
    NavicIconsPackage       = { link = "Type" },
    NavicIconsClass         = { link = "Type" },
    NavicIconsMethod        = { link = "Function" },
    NavicIconsProperty      = { link = "@property" },
    NavicIconsField         = { link = "@variable.member" },
    NavicIconsConstructor   = { link = "@constructor" },
    NavicIconsEnum          = { link = "Structure" },
    NavicIconsInterface     = { link = "Type" },
    NavicIconsFunction      = { link = "Function" },
    NavicIconsVariable      = { link = "@variable" },
    NavicIconsConstant      = { link = "Constant" },
    NavicIconsString        = { link = "String" },
    NavicIconsNumber        = { link = "Number" },
    NavicIconsBoolean       = { link = "Boolean" },
    NavicIconsArray         = { link = "Type" },
    NavicIconsObject        = { link = "Type" },
    NavicIconsKey           = { link = "Identifier" },
    NavicIconsKeyword       = { link = "Keyword" },
    NavicIconsNull          = { link = "Type" },
    NavicIconsEnumMember    = { link = "Constant" },
    NavicIconsStruct        = { link = "Structure" },
    NavicIconsEvent         = { link = "Structure" },
    NavicIconsOperator      = { link = "Operator" },
    NavicIconsTypeParameter = { link = "Type" },
    NavicText               = { fg = p.fg, bg = p.none },
    NavicSeparator          = { fg = p.gray4, bg = p.none },
}
