local p = require("kanagawa_dragon_blur.palette")

return {
    NavicIconsFile          = { fg = p.blue, bg = p.none },
    NavicIconsModule        = { fg = p.orange, bg = p.none },
    NavicIconsNamespace     = { fg = p.cyan, bg = p.none },
    NavicIconsPackage       = { fg = p.yellow, bg = p.none },
    NavicIconsClass         = { fg = p.red, bg = p.none },
    NavicIconsMethod        = { fg = p.purple, bg = p.none },
    NavicIconsProperty      = { fg = p.green, bg = p.none },
    NavicIconsField         = { fg = p.bright_green, bg = p.none },
    NavicIconsConstructor   = { fg = p.orange, bg = p.none },
    NavicIconsEnum          = { fg = p.enum, bg = p.none },
    NavicIconsInterface     = { fg = p.magenta, bg = p.none },
    NavicIconsFunction      = { fg = p.bright_blue, bg = p.none },
    NavicIconsVariable      = { fg = p.fg, bg = p.none },
    NavicIconsConstant      = { fg = p.constant, bg = p.none },
    NavicIconsString        = { fg = p.string, bg = p.none },
    NavicIconsNumber        = { fg = p.number, bg = p.none },
    NavicIconsBoolean       = { fg = p.bright_yellow, bg = p.none },
    NavicIconsArray         = { fg = p.cyan, bg = p.none },
    NavicIconsObject        = { fg = p.gray3, bg = p.none },
    NavicIconsKey           = { fg = p.purple, bg = p.none },
    NavicIconsKeyword       = { fg = p.keyword, bg = p.none },
    NavicIconsNull          = { fg = p.gray5, bg = p.none },
    NavicIconsEnumMember    = { fg = p.bright_magenta, bg = p.none },
    NavicIconsStruct        = { fg = p.orange, bg = p.none },
    NavicIconsEvent         = { fg = p.bright_red, bg = p.none },
    NavicIconsOperator      = { fg = p.operator, bg = p.none },
    NavicIconsTypeParameter = { fg = p.type, bg = p.none },
    NavicText               = { fg = p.fg, bg = p.none },
    NavicSeparator          = { fg = p.gray4, bg = p.none },
}
