local p = require("kanagawa_dragon_blur.palette")

return {
  NotifyBackground = { fg = p.fg, bg = "NONE" },
  NotifyERRORBorder = { fg = p.red, bg = "NONE" },
  NotifyWARNBorder = { fg = p.yellow, bg = "NONE" },
  NotifyINFOBorder = { fg = p.blue, bg = "NONE" },
  NotifyDEBUGBorder = { fg = p.ui_secondary, bg = "NONE" },
  NotifyTRACEBorder = { fg = p.purple, bg = "NONE" },
  NotifyERRORIcon = { fg = p.red },
  NotifyWARNIcon = { fg = p.yellow },
  NotifyINFOIcon = { fg = p.blue },
  NotifyDEBUGIcon = { fg = p.ui_secondary },
  NotifyTRACEIcon = { fg = p.purple },
  NotifyERRORTitle = { fg = p.red },
  NotifyWARNTitle = { fg = p.yellow },
  NotifyINFOTitle = { fg = p.blue },
  NotifyDEBUGTitle = { fg = p.ui_secondary },
  NotifyTRACETitle = { fg = p.purple },
  NotifyERRORBody = { fg = p.fg, bg = "NONE" },
  NotifyWARNBody = { fg = p.fg, bg = "NONE" },
  NotifyINFOBody = { fg = p.fg, bg = "NONE" },
  NotifyDEBUGBody = { fg = p.fg, bg = "NONE" },
  NotifyTRACEBody = { fg = p.fg, bg = "NONE" },
}
