local p = require("kanagawa_dragon_blur.palette")
return {
	RenderMarkdownCode = { bg = p.surface },
	RenderMarkdownCodeInline = { fg = p.string },
	RenderMarkdownBullet = { fg = p.cyan },
	RenderMarkdownH1Bg = { bg = "NONE", fg = p.title },
	RenderMarkdownH2Bg = { bg = "NONE", fg = p.title },
	RenderMarkdownH3Bg = { bg = "NONE", fg = p.title },
	RenderMarkdownH4Bg = { bg = "NONE", fg = p.title },
	RenderMarkdownH5Bg = { bg = "NONE", fg = p.title },
	RenderMarkdownH6Bg = { bg = "NONE", fg = p.title },
	RenderMarkdownH1 = { bg = "NONE", fg = p.title, bold = true },
	RenderMarkdownH2 = { bg = "NONE", fg = p.title, bold = true },
	RenderMarkdownH3 = { bg = "NONE", fg = p.title, bold = true },
	RenderMarkdownH4 = { bg = "NONE", fg = p.title, bold = true },
	RenderMarkdownH5 = { bg = "NONE", fg = p.title, bold = true },
	RenderMarkdownH6 = { bg = "NONE", fg = p.title, bold = true },
	RenderMarkdownTableHead = { fg = "NONE" },
	RenderMarkdownTableRow = { fg = "NONE" },
}
